# Generated by Django 5.2.7 on 2026-09-27 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_date', models.DateField()),
                ('person_name', models.CharField(max_length=100)),
                ('base_name', models.CharField(max_length=100)),
                ('equipment_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
